### ISSUE TITLE
Update to 0.86.0

### ISSUE THREAD

**Issue by arnaudmiribel** [daniellewisDL/streamlit-cheat-sheet#8]
Based on changelog [here](https://docs.streamlit.io/en/stable/changelog.html) I'd identify the following things to be done:
- [ ] 0.81.1 - Addition of `st.form()` and `st.form_submit_button()`
- [ ] 0.81.1 - Addition of `st.caption()`
- [ ] 0.84.0 - Addition of `st.session_state()`
- [ ] 0.86.0 - You can now use `st.columns`, `st.container` and `st.expander` without the `beta_` prefix.

**Comment by daniellewisDL** [comment]
Thanks for the pull request @arnaudmiribel! Very useful. Now merged, so issue fixed.
